services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173" # Viteのデフォルトポートをマッピング
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true